### ISSUE TITLE
Amazing

### ISSUE THREAD

**Issue by lukasmartinelli** [rastapasta/tilegrinder#1]
Thanks for this!!!! This is so convenient - I just wanted to filter layers in MBTiles, started out writing tilelive code, searching for a way to reencode - and luckily found this :heart:

I need to build a tool to filter out layers - to trim down fat vector tiles.
Will share the repo once finished.

You should get more stars.
Amazing work! Thanks.

**Comment by lukasmartinelli** [comment]
Will be used to trim down [OSM2VectorTiles](http://osm2vectortiles.org/) MBTiles.

The fact I can write my entire use case in so few lines of code is amazing :heart: :pray: 
Really well thought through!!

**Comment by rastapasta** [comment]
Hey hey @lukasmartinelli! Thanks for your lovely feedback 😊 

I'm very excited to see this library being used exactly for what I had it in mind for!

Happy that it could help you out and even more happy that you created another open source thingy using it - great work!

Cheers from Germany! 🍺
